Destination = input("Enter a destination: ")
Emotion = input("Enter an emotion: ")
Food = input("Enter a food: ")
Adjective = input("Enter an adjective: ")
Number = input("Enter a number: ")
Transportation = input("Enter a mode of transportation: ")
Verb = input("Enter an action verb: ")
Number_Two = input("Enter a number: ")
Food_Two = input("Enter a food: ")
Adjective_Two = input("Enter an adjective: ")
Verb_Two = input("Enter an action verb: ")
Adjective_Three = input("Enter an adjective: ")

print ("this is your family vacation!")
print (" Me and my family are on a vacation to " + Destination + " . I am very " + Emotion + " about it. On the plane we ate "+ Food + ". It was a very " + Adjective + " ride. When we landed it was " + Number + " degrees. We took a " + Transportation + " to the hotel, and I " + Verb + " to our room. After a " + Number_Two + " minute nap, we went to dinner and ate " + Food_Two + ". It was a very " + Adjective_Two + " meal. We " + Verb_Two + " home and went to sleep. What a " + Adjective_Three + " day! ") 
#Use of this page is optional. If you use code here, make sure either import page1 or from page1 import * appear on your main.py page.