Number =input("Enter a number: ")
Food =input("Enter a food: ")
Drink =input("Enter a drink: ")
Animal =input("Enter an animal: ")
Animal_2 =input("Enter another animal: ")
Action_verb =input("Enter an action verb: ")
Adjective =input("Enter an adjective: ")
Activity = input("Enter an activity: ")
Animal_3 =input("Enter an activity: ")
Adjective_2 =input("Enter an adjective: ")

print ("Spend a day in the woods!")
print (" I spent " + Number + " days in the woods. I lived off of " + Food + " and " + Drink + " with only my pet " + Animal + " to keep me company. During my stay I encountered many wild " + Animal_2 + " but I quickly became friends with them. Every morning, I would " + Action_verb + " to the stream to clean myself after a " + Adjective + " day of hiking. Hiking is one of my favrite pastimes because it very calming and also a good workout. However, when I wasn't hiking, I would spend my time " + Activity + " with some " + Animal_3 + " I found in the woods. At night I would sleep under the stars and relect on my " + Adjective_2 + " day. ")