Name = input("Enter a name")
Name_Two = input("Enter a name")
Adjective = input("Enter an adjective")
Number = input ("Enter a number")
Beach_activity = input("Enter a beach activity")
Number_Two = input ("Enter a number")
Adjective_Two = input("Enter an adjective")
Noun = input("Enter a noun")
Action_Verb = input("Enter an action verb")
Adjective_Three = input("Enter an adjective")
Number_Three = input("Enter a number")
Animal = input("Enter an animal")
Adjective_Four = input ("Enter an adjective")

print ("This is your trip to the beach!")
print (" Me and my friends " + Name + " and " + Name_Two + "Go with my " + Adjective + " father to the beach. It is " + Number + " degrees outside, so I can't wait to " + Beach_activity + " . After a " + Number_Two + " mile car ride we finally reach the " + Adjective_Two + " Beach. We decide to make sandcastles but to be honest they looked more like sand " + Noun + " . After this we " + Action_Verb + " into the water. The water was very " + Adjective_Three + " After swimming for about " + Number_Three + " minutes, we come across a sea " + Animal + " . It bit me so we had to rush home. What a " + Adjective_Four + " day at the beach! ") 